import {FastCommentsIconType} from "../types/icon";

export const DefaultIcons: Record<FastCommentsIconType, string> = {
    [FastCommentsIconType.APPROVE]: 'approve.svg',
    [FastCommentsIconType.BAN]: 'ban.svg',
    [FastCommentsIconType.BUBBLE]: 'text_bubble_dark.svg',
    [FastCommentsIconType.BUBBLE_WHITE]: 'text_bubble_white.svg',
    [FastCommentsIconType.CROSS]: 'close.svg',
    [FastCommentsIconType.REPLY_ARROW_INACTIVE]: 'reply_inactive.svg',
    [FastCommentsIconType.REPLY_ARROW_ACTIVE]: 'reply.svg',
    [FastCommentsIconType.UP]: 'thumbs_up_light.svg',
    [FastCommentsIconType.UP_ACTIVE]: 'thumbs_up_dark.svg',
    [FastCommentsIconType.DOWN]: 'thumbs_down_light.svg',
    [FastCommentsIconType.DOWN_ACTIVE]: 'thumbs_down_dark.svg',
    [FastCommentsIconType.PIN_BIG]: 'pin.svg',
    [FastCommentsIconType.UNPIN_BIG]: 'pin_unpin.svg',
    [FastCommentsIconType.PIN_SMALL]: 'pin.svg',
    [FastCommentsIconType.EDIT_SMALL]: 'edit.svg',
    [FastCommentsIconType.EDIT_BIG]: 'edit.svg',
    [FastCommentsIconType.TRASH]: 'trash_thin.svg',
    [FastCommentsIconType.EYE]: 'view.svg',
    [FastCommentsIconType.EYE_SLASH]: 'view_hide.svg',
    [FastCommentsIconType.REPLIED]: 'replied.svg',
    [FastCommentsIconType.BOLD]: 'editor_bold.svg',
    [FastCommentsIconType.UNDERLINE]: 'editor_underline.svg',
    [FastCommentsIconType.ITALIC]: 'editor_itallic.svg',
    [FastCommentsIconType.STRIKETHROUGH]: 'editor_strike.svg',
    [FastCommentsIconType.CODE]: 'editor_embed.svg',
    [FastCommentsIconType.LINK]: 'editor_link.svg',
    [FastCommentsIconType.IMAGE_UPLOAD]: 'editor_image.svg',
    [FastCommentsIconType.RETURN]: 'return.svg',
    [FastCommentsIconType.GIF]: 'bell.svg',
    [FastCommentsIconType.IP]: 'ip.svg',
    [FastCommentsIconType.BELL]: 'bell.svg',
    [FastCommentsIconType.BELL_RED]: 'bell-red.svg',
    [FastCommentsIconType.BLOCK]: 'ban.svg',
    [FastCommentsIconType.FLAG]: 'flag.svg',
};
