import {FastCommentsIconType, IconConfig} from "../types/icon";
import {Image} from "react-native";
import * as React from 'react';

export const DefaultIcons: IconConfig = {
    [FastCommentsIconType.APPROVE]: () => React.createElement(Image, {source: require('./icons/approve.svg')}),
    [FastCommentsIconType.BAN]: () => React.createElement(Image, {source: require('./icons/ban.svg')}),
    [FastCommentsIconType.BUBBLE]: () => React.createElement(Image, {source: require('./icons/text_bubble_dark.svg')}),
    [FastCommentsIconType.BUBBLE_WHITE]: () => React.createElement(Image, {source: require('./icons/text_bubble_white.svg')}),
    [FastCommentsIconType.CROSS]: () => React.createElement(Image, {source: require('./icons/close.svg')}),
    [FastCommentsIconType.REPLY_ARROW_INACTIVE]: () => React.createElement(Image, {source: require('./icons/reply_inactive.svg')}),
    [FastCommentsIconType.REPLY_ARROW_ACTIVE]: () => React.createElement(Image, {source: require('./icons/reply.svg')}),
    [FastCommentsIconType.UP]: () => React.createElement(Image, {source: require('./icons/thumbs_up_light.svg')}),
    [FastCommentsIconType.UP_ACTIVE]: () => React.createElement(Image, {source: require('./icons/thumbs_up_dark.svg')}),
    [FastCommentsIconType.DOWN]: () => React.createElement(Image, {source: require('./icons/thumbs_down_light.svg')}),
    [FastCommentsIconType.DOWN_ACTIVE]: () => React.createElement(Image, {source: require('./icons/thumbs_down_dark.svg')}),
    [FastCommentsIconType.PIN_BIG]: () => React.createElement(Image, {source: require('./icons/pin.svg')}),
    [FastCommentsIconType.UNPIN_BIG]: () => React.createElement(Image, {source: require('./icons/pin_unpin.svg')}),
    [FastCommentsIconType.PIN_SMALL]: () => React.createElement(Image, {source: require('./icons/pin.svg')}),
    [FastCommentsIconType.EDIT_SMALL]: () => React.createElement(Image, {source: require('./icons/edit.svg')}),
    [FastCommentsIconType.EDIT_BIG]: () => React.createElement(Image, {source: require('./icons/edit.svg')}),
    [FastCommentsIconType.TRASH]: () => React.createElement(Image, {source: require('./icons/trash_thin.svg')}),
    [FastCommentsIconType.EYE]: () => React.createElement(Image, {source: require('./icons/view.svg')}),
    [FastCommentsIconType.EYE_SLASH]: () => React.createElement(Image, {source: require('./icons/view_hide.svg')}),
    [FastCommentsIconType.REPLIED]: () => React.createElement(Image, {source: require('./icons/replied.svg')}),
    [FastCommentsIconType.BOLD]: () => React.createElement(Image, {source: require('./icons/editor_bold.svg')}),
    [FastCommentsIconType.UNDERLINE]: () => React.createElement(Image, {source: require('./icons/editor_underline.svg')}),
    [FastCommentsIconType.ITALIC]: () => React.createElement(Image, {source: require('./icons/editor_itallic.svg')}),
    [FastCommentsIconType.STRIKETHROUGH]: () => React.createElement(Image, {source: require('./icons/editor_strike.svg')}),
    [FastCommentsIconType.CODE]: () => React.createElement(Image, {source: require('./icons/editor_embed.svg')}),
    [FastCommentsIconType.LINK]: () => React.createElement(Image, {source: require('./icons/editor_link.svg')}),
    [FastCommentsIconType.IMAGE_UPLOAD]: () => React.createElement(Image, {source: require('./icons/editor_image.svg')}),
    [FastCommentsIconType.RETURN]: () => React.createElement(Image, {source: require('./icons/return.svg')}),
    [FastCommentsIconType.GIF]: () => React.createElement(Image, {source: require('./icons/bell.svg')}),
    [FastCommentsIconType.IP]: () => React.createElement(Image, {source: require('./icons/ip.svg')}),
    [FastCommentsIconType.BELL]: () => React.createElement(Image, {source: require('./icons/bell.svg')}),
    [FastCommentsIconType.BELL_RED]: () => React.createElement(Image, {source: require('./icons/bell.svg')}),
    [FastCommentsIconType.BLOCK]: () => React.createElement(Image, {source: require('./icons/ban.svg')}),
    [FastCommentsIconType.FLAG]: () => React.createElement(Image, {source: require('./icons/flag.svg')}),
};
