import {FastCommentsIconType, IconConfig} from "../types/icon";

export const DefaultIcons: IconConfig = {
    [FastCommentsIconType.APPROVE]: require('./icons/approve.png'),
    [FastCommentsIconType.BAN]: require('./icons/ban.png'),
    [FastCommentsIconType.BUBBLE]: require('./icons/text_bubble_dark.png'),
    [FastCommentsIconType.BUBBLE_WHITE]: require('./icons/text_bubble_white.png'),
    [FastCommentsIconType.CROSS]: require('./icons/close.png'),
    [FastCommentsIconType.REPLY_ARROW_INACTIVE]: require('./icons/reply_inactive.png'),
    [FastCommentsIconType.REPLY_ARROW_ACTIVE]: require('./icons/reply.png'),
    [FastCommentsIconType.UP]: require('./icons/thumbs_up_light.png'),
    [FastCommentsIconType.UP_ACTIVE]: require('./icons/thumbs_up_dark.png'),
    [FastCommentsIconType.DOWN]: require('./icons/thumbs_down_light.png'),
    [FastCommentsIconType.DOWN_ACTIVE]: require('./icons/thumbs_down_dark.png'),
    [FastCommentsIconType.PIN_BIG]: require('./icons/pin.png'),
    [FastCommentsIconType.UNPIN_BIG]: require('./icons/pin_unpin.png'),
    [FastCommentsIconType.PIN_SMALL]: require('./icons/pin.png'),
    [FastCommentsIconType.PIN_RED]: require('./icons/pin-red.png'),
    [FastCommentsIconType.EDIT_SMALL]: require('./icons/edit.png'),
    [FastCommentsIconType.EDIT_BIG]: require('./icons/edit.png'),
    [FastCommentsIconType.TRASH]: require('./icons/trash_thin.png'),
    [FastCommentsIconType.EYE]: require('./icons/view.png'),
    [FastCommentsIconType.EYE_SLASH]: require('./icons/view_hide.png'),
    [FastCommentsIconType.REPLIED]: require('./icons/replied.png'),
    [FastCommentsIconType.BOLD]: require('./icons/editor_bold.png'),
    [FastCommentsIconType.UNDERLINE]: require('./icons/editor_underline.png'),
    [FastCommentsIconType.ITALIC]: require('./icons/editor_itallic.png'),
    [FastCommentsIconType.STRIKETHROUGH]: require('./icons/editor_strike.png'),
    [FastCommentsIconType.CODE]: require('./icons/editor_embed.png'),
    [FastCommentsIconType.LINK]: require('./icons/editor_link.png'),
    [FastCommentsIconType.IMAGE_UPLOAD]: require('./icons/editor_image.png'),
    [FastCommentsIconType.RETURN]: require('./icons/return.png'),
    [FastCommentsIconType.GIF]: require('./icons/bell.png'),
    [FastCommentsIconType.IP]: require('./icons/ip.png'),
    [FastCommentsIconType.BELL]: require('./icons/bell.png'),
    [FastCommentsIconType.BELL_RED]: require('./icons/bell.png'),
    [FastCommentsIconType.BLOCK]: require('./icons/ban.png'),
    [FastCommentsIconType.FLAG]: require('./icons/flag.png'),
};
